function normalizeSources(list){return (Array.isArray(list)?list:[]).map(function(s){return Object.assign({},s,{plans:(s.plans||[]).map(function(p){var service=String(p.service||'IPTV').replace(/^CS Satélite$/,'TV Satélite').replace(/^CS NET$/,'TV Cabo');return Object.assign({},p,{service:service});})});});}
const API='https://fvttsguxeocisqvcrbqh.supabase.co/functions/v1/jstech-prime-public-api';
const WHATSAPP='5527997314781';
const fallback=[{source_key:'plenocs',name:'Pleno CS',plans:[{name:'Mensal',price:20,months:1,service:'TV Satélite'},{name:'Trimestral',price:55,months:3,service:'TV Satélite'},{name:'Semestral',price:100,months:6,service:'TV Satélite'},{name:'Anual',price:150,months:12,service:'TV Satélite'},{name:'Mensal',price:20,months:1,service:'TV Cabo'},{name:'Mensal',price:25,months:1,service:'IPTV'},{name:'Trimestral',price:65,months:3,service:'IPTV'},{name:'Semestral',price:120,months:6,service:'IPTV'},{name:'Anual',price:210,months:12,service:'IPTV'}],compatibility:['Smart TV','TV Box','Celular','Computador']},{source_key:'questbr',name:'Quest BR',plans:[{name:'Mensal',price:25,months:1,service:'IPTV'},{name:'Trimestral',price:65,months:3,service:'IPTV'},{name:'Semestral',price:130,months:6,service:'IPTV'},{name:'Anual',price:250,months:12,service:'IPTV'}],compatibility:['Android TV','Fire TV Stick','Chromecast','Roku','Android','iPhone','Notebook','PC','iPad','Apple TV']}];
let sources=fallback,csService='TV Satélite',iptvSource='plenocs';
const money=v=>Number(v||0).toLocaleString('pt-BR',{minimumFractionDigits:2,maximumFractionDigits:2});
const uniq=a=>[...new Set(a.filter(Boolean))];
const wa=text=>`https://wa.me/${WHATSAPP}?text=${encodeURIComponent(text)}`;

function wireWhatsApp(){document.querySelectorAll('[data-wa]').forEach(el=>{let text='Olá! Vim pelo site da JSTech Prime e gostaria de conhecer os serviços.';if(el.dataset.wa==='trial')text='Olá! Vim pelo site da JSTech Prime e gostaria de solicitar um teste.';if(el.dataset.wa==='cs-trial')text='Olá! Vim pelo site da JSTech Prime e quero solicitar um teste de TV autorizada. Meu receptor é: ';if(el.dataset.wa==='iptv-trial')text='Olá! Vim pelo site da JSTech Prime e quero solicitar um teste de IPTV. Meu aparelho é: ';if(el.dataset.wa==='support')text='Olá! Vim pelo site da JSTech Prime e preciso de ajuda para escolher entre TV autorizada e TV online.';el.href=wa(text);el.target='_blank';el.rel='noopener noreferrer'})}
function sourceName(source){return source?.name||({plenocs:'Pleno IPTV',questbr:'Quest IPTV'}[source?.source_key]||'IPTV')}
function plansFor(service,sourceKey){const all=sourceKey?sources.find(s=>s.source_key===sourceKey)?.plans||[]:sources.flatMap(s=>s.plans||[]);return all.filter(p=>(p.service||'IPTV')===service).sort((a,b)=>(a.months||1)-(b.months||1))}
function planCards(plans,kind,label){if(!plans.length)return'<div class="plan"><h3>Atualizando planos…</h3><p>O último catálogo válido será carregado em instantes.</p></div>';const max=Math.max(...plans.map(p=>Number(p.months)||1));return plans.map(p=>{const months=Number(p.months)||1,featured=months===max&&plans.length>1,eq=p.monthly_equivalent||Number(p.price)/months;const msg=`Olá! Vim pelo site da JSTech Prime e quero ${label}, plano ${p.name}, por R$ ${money(p.price)}.`;return `<article class="plan ${featured?'featured':''}"><small class="tag">${featured?'MELHOR CUSTO':months===1?'PARA COMEÇAR':'ECONOMIZE MAIS'}</small><h3>${p.name}</h3><div class="price"><span>R$</span><b>${money(p.price)}</b></div><div class="equivalent">${months>1?`equivale a R$ ${money(eq)} por mês`:'pagamento mensal'}</div><ul><li>Teste quando disponível</li><li>Ativação rápida</li><li>Suporte pelo WhatsApp</li><li>Sem fidelidade obrigatória</li></ul><a class="button ${kind==='cs'?'cs-button':'iptv-button'}" href="${wa(msg)}" target="_blank">ESCOLHER PLANO →</a></article>`}).join('')}
function renderCS(){const tabs=document.getElementById('csTabs');tabs.innerHTML=['TV Satélite','TV Cabo'].map(s=>`<button class="${s===csService?'active':''}" data-service="${s}">${s}</button>`).join('');tabs.querySelectorAll('button').forEach(b=>b.onclick=()=>{csService=b.dataset.service;renderCS()});document.getElementById('csPlans').innerHTML=planCards(plansFor(csService),'cs',csService)}
function renderIPTV(){const available=sources.filter(s=>(s.plans||[]).some(p=>(p.service||'IPTV')==='IPTV'));if(!available.some(s=>s.source_key===iptvSource))iptvSource=available[0]?.source_key;const tabs=document.getElementById('iptvTabs');tabs.innerHTML=available.map(s=>`<button class="${s.source_key===iptvSource?'active':''}" data-source="${s.source_key}">${sourceName(s)}</button>`).join('');tabs.querySelectorAll('button').forEach(b=>b.onclick=()=>{iptvSource=b.dataset.source;renderIPTV()});const source=available.find(s=>s.source_key===iptvSource);document.getElementById('iptvPlans').innerHTML=planCards(plansFor('IPTV',iptvSource),'iptv',`IPTV ${sourceName(source)}`)}
function renderDevices(){const devices=uniq(sources.flatMap(s=>s.compatibility||[]));const icons=['📺','▣','▯','⌨','◫','◇'];document.getElementById('deviceList').innerHTML=devices.slice(0,12).map((d,i)=>`<article>${icons[i%icons.length]}<b>${d}</b></article>`).join('');const dates=sources.map(s=>new Date(s.fetched_at||0)).filter(d=>d.getTime()>0);if(dates.length)document.getElementById('lastUpdate').textContent='Atualizado: '+new Date(Math.max(...dates)).toLocaleString('pt-BR')}
async function load(){try{const r=await fetch(API,{cache:'no-store'});if(!r.ok)throw 0;const p=await r.json();if(Array.isArray(p.sources)&&p.sources.length)sources=normalizeSources(p.sources)}catch(e){console.warn('Catálogo de segurança ativo')}renderCS();renderIPTV();renderDevices()}
document.querySelectorAll('.faq button').forEach(btn=>btn.onclick=()=>{const item=btn.closest('.faq'),open=item.classList.contains('open');document.querySelectorAll('.faq.open').forEach(x=>x.classList.remove('open'));if(!open)item.classList.add('open')});
const form=document.getElementById('leadForm');form?.addEventListener('submit',async e=>{e.preventDefault();const status=document.getElementById('formStatus'),button=form.querySelector('button');const data=Object.fromEntries(new FormData(form).entries());if(String(data.nome||'').trim().length<2||String(data.whatsapp||'').replace(/\D/g,'').length<8||!data.servico){status.textContent='Preencha nome, WhatsApp e serviço.';return}button.disabled=true;button.textContent='ENVIANDO…';try{const r=await fetch(API,{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify(data)});if(!r.ok)throw 0;status.textContent='Solicitação enviada com sucesso!';form.reset()}catch{status.textContent='Não foi possível enviar. Use o WhatsApp.'}finally{button.disabled=false;button.textContent='ENVIAR SOLICITAÇÃO →'}});
wireWhatsApp();load();

(function(){
  var toggle=document.getElementById('chatToggle'), panel=document.getElementById('chatPanel'), close=document.getElementById('chatClose');
  var messages=document.getElementById('chatMessages'), form=document.getElementById('chatForm'), input=document.getElementById('chatInput');
  function add(text,kind){var el=document.createElement('div');el.className='chat-bubble '+kind;el.textContent=text;messages.appendChild(el);messages.scrollTop=messages.scrollHeight;return el}
  function openChat(){panel.hidden=false;toggle.setAttribute('aria-expanded','true')}
  function closeChat(){panel.hidden=true;toggle.setAttribute('aria-expanded','false')}
  function showContact(){
    if(document.getElementById('chatContact'))return;
    var box=document.createElement('div');box.id='chatContact';box.className='chat-contact';
    box.innerHTML='<div class="chat-contact-title">Quer que a equipe continue com você?</div><input id="chatName" placeholder="Seu nome" autocomplete="name" required><input id="chatPhone" placeholder="Seu WhatsApp" inputmode="tel" autocomplete="tel" required><label><input id="chatConsent" type="checkbox" required> Autorizo o contato da equipe.</label><button type="button" id="chatSendContact">Enviar contato</button><div id="chatContactStatus" role="status"></div>';
    messages.appendChild(box);messages.scrollTop=messages.scrollHeight;
    document.getElementById('chatSendContact').addEventListener('click',function(){
      var name=document.getElementById('chatName').value.trim(),phone=document.getElementById('chatPhone').value.trim(),consent=document.getElementById('chatConsent').checked,status=document.getElementById('chatContactStatus'),button=this;
      if(name.length<2||phone.replace(/\D/g,'').length<8||!consent){status.textContent='Preencha nome, WhatsApp e autorize o contato.';return}
      button.disabled=true;button.textContent='ENVIANDO...';status.textContent='';
      fetch(API,{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({nome:name,whatsapp:phone,servico:'Atendimento automático',mensagem:'Contato enviado pelo chat com consentimento.'})}).then(function(r){if(!r.ok)throw 0;return r.json()}).then(function(){status.textContent='Contato enviado. A equipe continuará pelo WhatsApp.';add('Perfeito, '+name+'! Recebemos seu contato.','bot');box.remove()}).catch(function(){status.textContent='Não foi possível enviar agora. Use o botão WhatsApp.'}).finally(function(){button.disabled=false;button.textContent='Enviar contato'});
    });
  }
  function reply(text){
    var t=String(text||'').toLowerCase(),reply='Posso ajudar com planos, teste, compatibilidade ou suporte. Escolha uma opção abaixo.';
    if(t.indexOf('plano')>=0)reply='Os planos aparecem na seção Planos. Posso registrar seu contato para a equipe confirmar a melhor opção.';
    else if(t.indexOf('teste')>=0)reply='O teste depende da disponibilidade e da compatibilidade do seu aparelho. Vou registrar seu pedido para a equipe confirmar.';
    else if(t.indexOf('suporte')>=0||t.indexOf('ajuda')>=0)reply='Claro. Informe o modelo do aparelho e o que aconteceu. A equipe recebe seu contato e continua o atendimento.';
    else if(t.indexOf('aparelho')>=0||t.indexOf('tv')>=0||t.indexOf('compat')>=0)reply='Atendemos Smart TV, TV Box, celular, tablet e computador compatíveis. Envie o modelo para conferirmos.';
    else if(t.indexOf('humano')>=0||t.indexOf('pessoa')>=0||t.indexOf('whatsapp')>=0){reply='Vou encaminhar você para o atendimento humano no WhatsApp.';setTimeout(function(){window.open(wa('Olá! Vim pelo atendimento automático da JSTech Prime e preciso falar com a equipe.'),'_blank')},500)}
    var typing=add('Digitando...','bot typing');setTimeout(function(){typing.remove();add(reply,'bot');if(t.indexOf('humano')<0&&t.indexOf('pessoa')<0)showContact()},420);
  }
  toggle&&toggle.addEventListener('click',function(){panel.hidden?openChat():closeChat()});close&&close.addEventListener('click',closeChat);
  document.querySelectorAll('[data-chat]').forEach(function(b){b.addEventListener('click',function(){openChat();add(b.textContent,'user');reply(b.dataset.chat||b.textContent)})});
  form&&form.addEventListener('submit',function(e){e.preventDefault();var text=input.value.trim();if(!text)return;add(text,'user');input.value='';reply(text)});
  setTimeout(function(){if(panel&&panel.hidden)openChat()},2400);
})();
(function(){
  var PROMO_API='https://fvttsguxeocisqvcrbqh.supabase.co/functions/v1/jstech-prime-site';
  var form=document.getElementById('promoForm');if(!form)return;var status=document.getElementById('promoStatus');
  form.addEventListener('submit',function(e){e.preventDefault();var email=(new FormData(form).get('email')||'').toString().trim().toLowerCase();if(!email){status.textContent='Informe um e-mail válido.';return}var button=form.querySelector('button');button.disabled=true;button.textContent='CADASTRANDO...';status.textContent='';
    fetch(PROMO_API,{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({nome:'Lista de promoções',whatsapp:'email:'+email,servico:'Promoções',mensagem:'Consentimento confirmado para receber novidades.'})}).then(function(r){if(!r.ok)throw 0;return r.json()}).then(function(){status.textContent='Cadastro recebido. Você só receberá mensagens com seu consentimento.';form.reset()}).catch(function(){status.textContent='Não foi possível cadastrar agora. Tente novamente ou fale pelo WhatsApp.'}).finally(function(){button.disabled=false;button.textContent='QUERO RECEBER →'});
  });
})();